//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nurse
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NurseEntities : DbContext
    {
        public NurseEntities()
            : base("name=nurseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<educates> educates { get; set; }
        public virtual DbSet<nurse_list> nurse_list { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<train> train { get; set; }
    }
}
